ALTER TABLE pipeline_run_references
ADD COLUMN IF NOT EXISTS execution_order INTEGER,
ADD COLUMN IF NOT EXISTS step_label TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE pipeline_run_tools
ADD COLUMN IF NOT EXISTS usage_role TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();